//! Bug report bundle assembly + the per-section text renderers.
//! Per design D6, this module owns:
//! - Cache and input summaries (path/count metadata only — never contents)
//! - The bundle's `README.txt` and modal copy as `const &str` so the two
//!   stay in sync at edit time (D10)
//! - `build_bundle` (added in §7): the zip assembler
//!
//! Privacy invariant (proposal): the bundle MUST NEVER contain raw
//! research data (input files, cache contents, exports). Implementation
//! enforces this by only ever surfacing path/size/mtime metadata for
//! cache files and path/count metadata for inputs.

use std::fmt::Write;
use std::fs;
use std::io::{Cursor, Write as IoWrite};
use std::path::Path;
use std::time::SystemTime;

use chrono::{DateTime, SecondsFormat, Utc};

use crate::app::{AppState, SessionInputs};

/// One-line privacy statement — appears verbatim both in the bundle's
/// `README.txt` and in the log-pane confirm modal (D10). Edits MUST
/// preserve the embed in [`BUNDLE_README_TEXT`] so the two never drift.
pub const BUNDLE_PRIVACY_LINE: &str = "Not included: cache file contents, the raw MS-DIAL .txt input, the metadata CSV, and any prior Stage 2/3 CSV/PNG exports. Absolute paths inside the bundle are redacted: your home directory becomes ~/ to avoid leaking your username.";

/// Plain-text preamble written verbatim as `README.txt` inside the
/// bundle. Embeds the canonical "Not included: cache file contents…"
/// privacy phrase so the modal and the README stay synchronised
/// (D10, enforced by `privacy_line_substring_appears_in_readme`).
pub const BUNDLE_README_TEXT: &str = concat!(
    "Metabolopan (v",
    env!("CARGO_PKG_VERSION"),
    ") — Metabolomic Enrichment Analysis — bug report bundle
=================================================================

This zip is a diagnostic snapshot generated by the desktop app's
[Download bug report…] button. It is intended for the project
maintainers (or yourself for record-keeping).

Contents:
  README.txt           this file
  version.txt          build identifiers (pkg version, git SHA, rustc, target)
  RUST_LOG.txt         the RUST_LOG directive captured at startup
  KEGG_CACHE_DIR.txt   the KEGG_CACHE_DIR env value at startup (or <unset>)
  logs.txt             current session log (file sink, INFO-level)
  app_state.txt        current AppState variant + user-facing parameters
  input_summary.txt    loaded input file paths + counts only
  cache_summary.txt    KEGG/PubChem cache file sizes + fetched-at ranges only

  Note: we never dump the full process environment — only the two
  named env vars above appear, one per file, so the filename names
  exactly what is inside.

Privacy:
  Not included: cache file contents, the raw MS-DIAL .txt input,
  the metadata CSV, and any prior Stage 2/3 CSV/PNG exports.
  Absolute paths inside this bundle are redacted: your home
  directory is replaced with ~/ so the bundle does not leak your
  username when shared publicly (e.g. in a GitHub issue).

If you found a bug, please attach this zip to your GitHub issue or
email — no follow-up data should be necessary for triage in the
common case.
"
);

// D10 invariant: the privacy phrasing must match between BUNDLE_PRIVACY_LINE
// (used by the modal) and the README's "Privacy:" paragraph. A runtime test
// (`privacy_line_substring_appears_in_readme` below) enforces this — we
// deliberately use a runtime test rather than a compile-time const assert
// because the README wraps the line across two indented rows, which a strict
// substring const check can't tolerate.

/// Renders the `cache_summary.txt` section: for every file under each
/// existing cache root, one line with name, byte size, mtime, and (for
/// structured JSON caches) the min/max `fetched_at` range. Cache
/// contents are NEVER emitted — only metadata.
///
/// Missing roots are silently omitted (no error). A file that fails
/// the `fetched_at` extraction still appears with size + mtime alone.
pub fn render_cache_summary(cache_roots: &[&Path]) -> String {
    let mut out = String::new();
    writeln!(out, "Cache summary (metadata only; no file contents)").ok();
    writeln!(out, "================================================").ok();
    let mut any_root = false;
    for root in cache_roots {
        if !root.exists() {
            continue;
        }
        any_root = true;
        writeln!(out).ok();
        writeln!(out, "Root: {}", root.display()).ok();
        let entries = match fs::read_dir(root) {
            Ok(rd) => rd,
            Err(e) => {
                writeln!(out, "  (failed to read directory: {e})").ok();
                continue;
            }
        };
        let mut paths: Vec<_> = entries.flatten().map(|e| e.path()).collect();
        paths.sort();
        for path in paths {
            if path.is_dir() {
                continue;
            }
            let name = path
                .file_name()
                .and_then(|s| s.to_str())
                .unwrap_or("<no name>");
            let (size, mtime) = file_meta(&path);
            write!(out, "  {name}  size={size}B  mtime={}", fmt_systime(mtime)).ok();
            if let Some((lo, hi)) = extract_fetched_at_range(&path) {
                writeln!(
                    out,
                    "  fetched_at_min={}  fetched_at_max={}",
                    lo.to_rfc3339_opts(SecondsFormat::Secs, true),
                    hi.to_rfc3339_opts(SecondsFormat::Secs, true),
                )
                .ok();
            } else {
                writeln!(out).ok();
            }
        }
    }
    if !any_root {
        writeln!(out, "(no cache roots present on disk)").ok();
    }
    out
}

/// Renders the `input_summary.txt` section: the loaded MS-DIAL paths
/// (single- or dual-mode), metadata CSV path, parsed feature/sample
/// counts, and per-group sample distribution. Never includes any cell
/// values from the loaded inputs.
pub fn render_input_summary(_state: &AppState, inputs: &SessionInputs) -> String {
    let mut out = String::new();
    writeln!(out, "Input summary (paths + counts only; no contents)").ok();
    writeln!(out, "==================================================").ok();
    // Post-refactor: loaded inputs are on `App::inputs`, not on the
    // `AppState` variant. The `_state` parameter is kept for API
    // continuity / future extension (e.g. annotating which screen the
    // bundle was requested from).
    let ion_tables: &[crate::data::IonModeTable] = inputs.ion_tables.as_slice();
    let mapping: Option<&crate::data::GroupMapping> = inputs.mapping.as_ref();
    let csv_path: Option<&std::path::PathBuf> = inputs.csv_path.as_ref();

    if ion_tables.is_empty() {
        writeln!(out, "ion_tables: <none loaded>").ok();
    } else {
        writeln!(out, "ion_tables_count: {}", ion_tables.len()).ok();
        for (i, t) in ion_tables.iter().enumerate() {
            let path = t
                .txt_path
                .as_ref()
                .map(|p| p.display().to_string())
                .unwrap_or_else(|| "<no path>".into());
            writeln!(
                out,
                "  ion_table[{i}]: mode={:?}  features={}  samples={}  path={}",
                t.mode,
                t.table.features.len(),
                t.table.sample_cols.len(),
                path
            )
            .ok();
        }
    }

    let csv = csv_path.map(|p| p.display().to_string());
    writeln!(out, "metadata_csv_path: {}", csv.unwrap_or("<none>".into())).ok();

    match mapping {
        None => {
            writeln!(out, "mapping: <none loaded>").ok();
        }
        Some(m) => {
            writeln!(out, "mapping_sample_count: {}", m.sample_count()).ok();
            writeln!(out, "mapping_assigned_count: {}", m.assigned_count()).ok();
            writeln!(out, "mapping_has_biosample: {}", m.has_biosample()).ok();
            let groups = m.groups_in_order();
            use std::collections::BTreeMap;
            let mut per_group: BTreeMap<String, usize> = BTreeMap::new();
            for (_, g) in &groups {
                *per_group.entry(g.clone()).or_insert(0) += 1;
            }
            for (g, c) in &per_group {
                writeln!(out, "  group[{g}]: {c} samples").ok();
            }
            let cols = m.metadata_column_names();
            writeln!(out, "metadata_columns: {cols:?}").ok();
        }
    }
    out
}

fn file_meta(path: &Path) -> (u64, SystemTime) {
    let meta = fs::metadata(path).ok();
    let size = meta.as_ref().map(|m| m.len()).unwrap_or(0);
    let mtime = meta
        .and_then(|m| m.modified().ok())
        .unwrap_or(SystemTime::UNIX_EPOCH);
    (size, mtime)
}

fn fmt_systime(t: SystemTime) -> String {
    let dt: DateTime<Utc> = t.into();
    dt.to_rfc3339_opts(SecondsFormat::Secs, true)
}

/// Walks the JSON tree at `path` and returns the min/max `fetched_at`
/// timestamps found among any object's `"fetched_at"` key. Handles the
/// five structured caches uniformly without needing per-cache schema
/// knowledge: works for file-level `fetched_at` (organisms.json,
/// <species>.json) and per-entry `fetched_at` (modules.json,
/// pubchem.json, cid_to_cpd.json).
fn extract_fetched_at_range(path: &Path) -> Option<(DateTime<Utc>, DateTime<Utc>)> {
    let bytes = fs::read(path).ok()?;
    let v: serde_json::Value = serde_json::from_slice(&bytes).ok()?;
    let mut ts: Vec<DateTime<Utc>> = Vec::new();
    collect_fetched_at(&v, &mut ts);
    if ts.is_empty() {
        return None;
    }
    ts.sort();
    Some((*ts.first()?, *ts.last()?))
}

/// Inputs for `build_bundle`. The caller assembles these on the UI
/// thread (so `&AppState` is borrowed only briefly) and hands the owned
/// strings + paths to the bundle assembler, which can then run on a
/// background thread (D8).
pub struct BundleArgs<'a> {
    /// Path to the current session's file sink log. `None` when the
    /// file sink failed to initialise at startup; `logs.txt` in the
    /// zip is a one-line stub in that case.
    pub session_log_path: Option<&'a Path>,
    /// `RUST_LOG` directive captured at startup.
    pub rust_log_directive: &'a str,
    /// `KEGG_CACHE_DIR` value if set at startup; `None` otherwise.
    pub kegg_cache_dir: Option<&'a str>,
    /// Pre-rendered `app_state.txt` content. Produced on the UI thread
    /// by `render_app_state(&app.state)` so the borrow doesn't escape.
    pub app_state_text: String,
    /// Pre-rendered `input_summary.txt` content. Produced on the UI
    /// thread by `render_input_summary(&app.state)`.
    pub input_summary_text: String,
    /// Pre-rendered `cache_summary.txt` content. Produced on the UI
    /// thread by `render_cache_summary(...)`.
    pub cache_summary_text: String,
}

/// Errors from `build_bundle`. All are IO or zip-encoding failures
/// surfaced to the UI thread so it can log + show the user.
#[derive(Debug, thiserror::Error)]
pub enum BundleError {
    #[error("zip encoding failed: {0}")]
    Zip(#[from] zip::result::ZipError),
    #[error("zip IO failed: {0}")]
    Io(#[from] std::io::Error),
}

/// Assembles the bug-report zip in memory and returns its bytes.
/// Pure function over `BundleArgs` — no environment lookups beyond
/// `HOME` / `USERPROFILE` (for path redaction); no file system access
/// except reading the session log file (if a path was supplied). All
/// other text sections are pre-rendered.
///
/// Privacy invariants:
/// - The produced zip contains exactly eight top-level files (listed
///   in [`BUNDLE_README_TEXT`]) and never any cache contents, raw
///   input files, or prior exports.
/// - Every text section that could carry user paths (RUST_LOG.txt,
///   KEGG_CACHE_DIR.txt, logs.txt, app_state.txt, input_summary.txt,
///   cache_summary.txt) is passed through [`redact_home_dir`] so the
///   user's home directory becomes `~`, preventing username leakage
///   when the bundle is shared publicly (e.g. attached to a public
///   GitHub issue). Only README.txt and version.txt are unredacted
///   (no user paths by construction).
pub fn build_bundle(args: BundleArgs<'_>) -> Result<Vec<u8>, BundleError> {
    let mut writer = zip::ZipWriter::new(Cursor::new(Vec::new()));
    let opts: zip::write::SimpleFileOptions = zip::write::SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated)
        .unix_permissions(0o644);

    // README + version: no user paths, no redaction needed.
    add_entry(
        &mut writer,
        "README.txt",
        BUNDLE_README_TEXT.as_bytes(),
        opts,
    )?;
    add_entry(
        &mut writer,
        "version.txt",
        render_version().as_bytes(),
        opts,
    )?;

    // Split env vars into per-variable files so the filename names
    // exactly what is inside — no risk of mistaking this for a full
    // env dump. A RUST_LOG directive is arbitrary user text and CAN
    // carry an absolute path (e.g. a file-target filter), so it is
    // redacted by construction like every other path-capable section.
    add_entry(
        &mut writer,
        "RUST_LOG.txt",
        format!("{}\n", redact_home_dir(args.rust_log_directive)).as_bytes(),
        opts,
    )?;
    let kegg_value = args.kegg_cache_dir.unwrap_or("<unset>");
    add_entry(
        &mut writer,
        "KEGG_CACHE_DIR.txt",
        format!("{}\n", redact_home_dir(kegg_value)).as_bytes(),
        opts,
    )?;

    // logs.txt may contain INFO/WARN lines with absolute paths
    // (cache dir, save-as target, etc.). Redact the whole text.
    let logs_text = String::from_utf8_lossy(&load_logs(args.session_log_path)).to_string();
    add_entry(
        &mut writer,
        "logs.txt",
        redact_home_dir(&logs_text).as_bytes(),
        opts,
    )?;

    add_entry(
        &mut writer,
        "app_state.txt",
        redact_home_dir(&args.app_state_text).as_bytes(),
        opts,
    )?;
    add_entry(
        &mut writer,
        "input_summary.txt",
        redact_home_dir(&args.input_summary_text).as_bytes(),
        opts,
    )?;
    add_entry(
        &mut writer,
        "cache_summary.txt",
        redact_home_dir(&args.cache_summary_text).as_bytes(),
        opts,
    )?;

    let cursor = writer.finish()?;
    Ok(cursor.into_inner())
}

/// Returns the user's home directory using cross-platform env vars
/// (`HOME` on Unix, `USERPROFILE` on Windows). Avoids both
/// `std::env::home_dir` (historically problematic on Windows) and the
/// `dirs`/`home` external crates to keep the dep tree lean (D9
/// principle).
fn home_directory() -> Option<String> {
    if let Some(p) = std::env::var_os("HOME") {
        let s = p.to_string_lossy().to_string();
        if !s.is_empty() {
            return Some(s);
        }
    }
    if let Some(p) = std::env::var_os("USERPROFILE") {
        let s = p.to_string_lossy().to_string();
        if !s.is_empty() {
            return Some(s);
        }
    }
    None
}

/// Replaces every occurrence of the current process's home directory
/// with `~` inside `text`. Safe to apply blanket — home directory
/// strings are specific enough that substring collisions in real log
/// text are negligible. Idempotent and a no-op when no home directory
/// is resolvable (returns input unchanged).
pub fn redact_home_dir(text: &str) -> String {
    match home_directory() {
        Some(home) => text.replace(&home, "~"),
        None => text.to_string(),
    }
}

fn add_entry(
    writer: &mut zip::ZipWriter<Cursor<Vec<u8>>>,
    name: &str,
    bytes: &[u8],
    opts: zip::write::SimpleFileOptions,
) -> Result<(), BundleError> {
    writer.start_file(name, opts)?;
    writer.write_all(bytes)?;
    Ok(())
}

fn render_version() -> String {
    let pkg = env!("CARGO_PKG_VERSION");
    let git = option_env!("GIT_SHA").unwrap_or("unknown");
    let rustc = option_env!("RUSTC_VERSION").unwrap_or("unknown");
    let arch = std::env::consts::ARCH;
    let os = std::env::consts::OS;
    let family = std::env::consts::FAMILY;
    let os_ver = os_version();
    format!(
        "pkg_version: {pkg}\n\
         git_sha: {git}\n\
         rustc_version: {rustc}\n\
         arch: {arch}\n\
         os: {os}\n\
         os_version: {os_ver}\n\
         family: {family}\n"
    )
}

/// Returns the host OS point-release version string, or `"unknown"`.
/// Used in `version.txt` inside the bug-report bundle to disambiguate
/// platform-specific rendering or font bugs across OS releases.
fn os_version() -> String {
    #[cfg(target_os = "macos")]
    {
        if let Ok(out) = std::process::Command::new("sw_vers")
            .arg("-productVersion")
            .output()
            && out.status.success()
        {
            let v = String::from_utf8_lossy(&out.stdout).trim().to_string();
            if !v.is_empty() {
                return v;
            }
        }
    }
    #[cfg(target_os = "linux")]
    {
        if let Ok(content) = std::fs::read_to_string("/etc/os-release") {
            for line in content.lines() {
                if let Some(v) = line.strip_prefix("VERSION_ID=") {
                    return v.trim_matches('"').to_string();
                }
            }
        }
    }
    // Windows: avoid the winreg dep; the broad OS name is sufficient for now.
    "unknown".to_string()
}

fn load_logs(path: Option<&Path>) -> Vec<u8> {
    match path {
        None => b"session log unavailable: file sink was not initialised this session.\n".to_vec(),
        Some(p) => match fs::read(p) {
            Ok(bytes) => bytes,
            Err(e) => format!(
                "session log unavailable: failed to read {}: {e}\n",
                p.display()
            )
            .into_bytes(),
        },
    }
}

fn collect_fetched_at(v: &serde_json::Value, out: &mut Vec<DateTime<Utc>>) {
    match v {
        serde_json::Value::Object(map) => {
            for (k, val) in map {
                if k == "fetched_at" {
                    if let Some(s) = val.as_str()
                        && let Ok(dt) = DateTime::parse_from_rfc3339(s)
                    {
                        out.push(dt.with_timezone(&Utc));
                    }
                } else {
                    collect_fetched_at(val, out);
                }
            }
        }
        serde_json::Value::Array(arr) => {
            for v in arr {
                collect_fetched_at(v, out);
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::app::AppState;
    use crate::data::types::FeatureMeta;
    use crate::data::{IonMode, IonModeTable, MetabolomicsTable};
    use ndarray::Array2;
    use tempfile::tempdir;

    fn make_minimal_table(features: usize, samples: usize) -> MetabolomicsTable {
        let arr = Array2::<f64>::zeros((features, samples));
        MetabolomicsTable {
            // All synthetic features have `inchikey: None`, so annotated_count is 0.
            annotated_count: 0,
            features: (0..features)
                .map(|i| FeatureMeta {
                    alignment_id: i.to_string(),
                    metabolite_name: format!("M{i}"),
                    inchikey: None,
                    adduct_type: None,
                    average_rt_min: None,
                    average_mz: None,
                    formula: None,
                    smiles: None,
                    fill_percent: None,
                    ms_ms_matched: None,
                    isotope_tracking_weight_number: None,
                    total_score: None,
                    sn_average: None,
                })
                .collect(),
            sample_cols: (0..samples).map(|j| format!("S{j}")).collect(),
            intensity_raw: arr.clone(),
            intensity: arr,
            excluded_cols: vec![],
        }
    }

    #[test]
    fn render_cache_summary_fake_root_with_modules_json_and_garbage() {
        let dir = tempdir().expect("tempdir");
        let modules_path = dir.path().join("modules.json");
        let garbage_path = dir.path().join("garbage.json");
        let now = Utc::now().to_rfc3339_opts(SecondsFormat::Secs, true);
        let modules_json = format!(
            "{{\"modules\":{{\"M00001\":{{\"id\":\"M00001\",\"fetched_at\":\"{now}\"}}}}}}"
        );
        std::fs::write(&modules_path, modules_json).unwrap();
        std::fs::write(&garbage_path, "not json at all").unwrap();

        let summary = render_cache_summary(&[dir.path()]);
        assert!(
            summary.contains("modules.json"),
            "modules.json missing from summary:\n{summary}"
        );
        assert!(
            summary.contains("garbage.json"),
            "garbage.json missing from summary:\n{summary}"
        );
        assert!(
            summary.contains("fetched_at_min="),
            "fetched_at range missing from modules.json line:\n{summary}"
        );
        // garbage.json must be present but WITHOUT a fetched_at_min line.
        let garbage_line = summary
            .lines()
            .find(|l| l.contains("garbage.json"))
            .expect("garbage line");
        assert!(
            !garbage_line.contains("fetched_at_min"),
            "garbage line should NOT have fetched_at_min: {garbage_line}"
        );
    }

    #[test]
    fn render_cache_summary_missing_root_is_silent() {
        let dir = tempdir().expect("tempdir");
        let missing = dir.path().join("does_not_exist");
        let summary = render_cache_summary(&[&missing]);
        assert!(
            summary.contains("(no cache roots present on disk)"),
            "missing-root sentinel absent:\n{summary}"
        );
    }

    #[test]
    fn render_input_summary_dual_mode() {
        let pos = IonModeTable {
            mode: IonMode::Positive,
            table: make_minimal_table(3, 4),
            txt_path: Some("/fixtures/POS.txt".into()),
        };
        let neg = IonModeTable {
            mode: IonMode::Negative,
            table: make_minimal_table(5, 4),
            txt_path: Some("/fixtures/NEG.txt".into()),
        };
        let state = AppState::Stage1Input {
            slot1_mode: Some(IonMode::Positive),
            slot2_revealed: true,
            slot2_mode: Some(IonMode::Negative),
            error: None,
        };
        let inputs = SessionInputs {
            ion_tables: vec![pos, neg],
            mapping: None,
            csv_path: Some("/fixtures/metadata.csv".into()),
        };
        let out = render_input_summary(&state, &inputs);
        assert!(
            out.contains("ion_tables_count: 2"),
            "expected 2 tables: {out}"
        );
        assert!(out.contains("/fixtures/POS.txt"), "POS path missing: {out}");
        assert!(out.contains("/fixtures/NEG.txt"), "NEG path missing: {out}");
        assert!(
            out.contains("features=3"),
            "POS feature count missing: {out}"
        );
        assert!(
            out.contains("features=5"),
            "NEG feature count missing: {out}"
        );
        assert!(
            out.contains("metadata_csv_path: /fixtures/metadata.csv"),
            "csv path missing: {out}"
        );
    }

    #[test]
    fn privacy_line_substring_appears_in_readme() {
        // D10 / L3.4: the modal's privacy phrasing must show up in the README too.
        // The README wraps it across two lines, so we check the salient phrase
        // ("Not included: cache file contents") appears in both surfaces.
        let key = "Not included: cache file contents";
        assert!(
            BUNDLE_PRIVACY_LINE.contains(key),
            "privacy line lost the canonical phrase"
        );
        assert!(
            BUNDLE_README_TEXT.contains(key),
            "README missing canonical privacy phrase — modal/README copy has drifted"
        );
    }

    #[test]
    fn render_input_summary_initializing_emits_minimal() {
        let (_tx, rx) = std::sync::mpsc::channel();
        let state = AppState::Initializing {
            load_rx: rx,
            fallback_cache: None,
            last_error: None,
        };
        let inputs = SessionInputs::default();
        let out = render_input_summary(&state, &inputs);
        assert!(out.contains("ion_tables: <none loaded>"));
        assert!(out.contains("mapping: <none loaded>"));
    }

    #[test]
    fn render_input_summary_carries_csv_path_through_stage3() {
        // Verifies the add-csv-path-throughout-stages invariant survives the
        // SessionSettings refactor: `app.inputs.csv_path` is readable from any
        // post-Stage-1 variant. Constructs the slim `Stage3EnrichResult`
        // variant + a populated `SessionInputs` and asserts the path appears
        // in the rendered summary.
        use crate::app::{AppState, RefreshState, SessionInputs};
        use crate::dam::DamMethod;
        use crate::dam::fdr::FdrMethod;
        use crate::dam::types::DamResult;
        use crate::enrichment::types::{EnrichmentDirection, EnrichmentResult};
        use std::collections::{HashMap, HashSet};

        let dam_result = DamResult {
            method: DamMethod::Welch,
            numerator: "T".into(),
            denominator: "N".into(),
            features: vec![],
            skipped: 0,
            fdr_method: FdrMethod::BenjaminiHochberg,
            dedup_report: None,
        };
        let enrichment_result = EnrichmentResult {
            universe_size: 0,
            dam_cpd_size: 0,
            direction: EnrichmentDirection::Both,
            min_hit_count: 1,
            min_entry_size: 1,
            entries_dropped_by_min_entry_size: 0,
            empty_compound_count: 0,
            rows: vec![],
            fdr_method: FdrMethod::BenjaminiHochberg,
        };
        let dir = tempdir().expect("tempdir");
        let csv_path = dir.path().join("m.csv");
        std::fs::write(&csv_path, "sample,group\nS1,A\nS2,B\n").unwrap();
        let mapping =
            crate::data::load_group_mapping(&csv_path, &["S1".to_string(), "S2".to_string()])
                .expect("load mapping");

        let state = AppState::Stage3EnrichResult {
            dam_results: vec![dam_result],
            module_retention: None,
            enrichment_result,
            mapped_universe: HashSet::new(),
            feature_to_cpds: HashMap::new(),
            pubchem_time_span: None,
            kegg_conv_time_span: None,
            dual_mode_breakdown: None,
            funnel: Default::default(),
            dotplot: None,
            rendering: false,
            render_rx: None,
            refresh_state: RefreshState::Idle,
            confirming_new_round: false,
            height_user_overridden: false,
        };
        let inputs = SessionInputs {
            ion_tables: vec![],
            mapping: Some(mapping),
            csv_path: Some(csv_path.clone()),
        };
        let out = render_input_summary(&state, &inputs);
        let needle = csv_path.display().to_string();
        assert!(
            out.contains(&needle),
            "metadata_csv_path should carry through to Stage 3 result:\nneedle={needle}\nout={out}"
        );
        assert!(
            !out.contains("metadata_csv_path: <none>"),
            "metadata_csv_path should not be <none> when csv_path is Some:\n{out}"
        );
    }
}
